### ISSUE TITLE
[1092:0605/115531.410:ERROR:print_render_frame_helper.cc(2264)] Printing failed.

### ISSUE THREAD

**Issue by janafsal** [Hubertformin/electron-pos-printer#107]
[1092:0605/115531.410:ERROR:print_render_frame_helper.cc(2264)] Printing failed.
@Hubertformin  could you please advice about this error

**Comment by janafsal** [comment]
this error occured when print while silent is true and while it is false it prints correctly

**Comment by Jerald042615** [comment]
Same error occurred on me when printing in silent.

**Comment by janafsal** [comment]
I could print correctly when i change pageSize: '80mm' instead of width property but the the error still shows in the terminal

**Comment by Jerald042615** [comment]
Ow really? What printer are you using? Mine shows error and not printing.

**Comment by Jerald042615** [comment]
const options = {
		silent: true,
    preview: false,
    margin: '0 0 0 0',
    copies: 1,
    printerName: 'POS-80C',
    timeOutPerLine: 4000,
    pageSize: "80mm" // page size
	}

	const data = [{
		type: 'text',                                       // 'text' | 'barCode' | 'qrCode' | 'image' | 'table
		value: 'SAMPLE HEADING',
		style: {fontWeight: "700", textAlign: 'center', fontSize: "24px"}
	}]

	PosPrinter.print(data, options).then(response => console.log(response)).catch(error => console.log(error))
	
	
	this is my configuration, 

And my error shows, 


[23996:0620/204757.414:ERROR:print_render_frame_helper.cc(2302)] Printing failed.
[TimedOutError] Make sure your printer is connected

**Comment by Jerald042615** [comment]
When silent is equals to false, I can print with print dialog. Which is not the behavior I want to.

**Comment by Jerald042615** [comment]
What version are you using by the way?

**Comment by janafsal** [comment]
> const options = { silent: true, preview: false, margin: '0 0 0 0', copies: 1, printerName: 'POS-80C', timeOutPerLine: 4000, pageSize: "80mm" // page size }
> 
> ```
> const data = [{
> 	type: 'text',                                       // 'text' | 'barCode' | 'qrCode' | 'image' | 'table
> 	value: 'SAMPLE HEADING',
> 	style: {fontWeight: "700", textAlign: 'center', fontSize: "24px"}
> }]
> 
> PosPrinter.print(data, options).then(response => console.log(response)).catch(error => console.log(error))
> 
> 
> this is my configuration, 
> ```
> 
> And my error shows,
> 
> [23996:0620/204757.414:ERROR:print_render_frame_helper.cc(2302)] Printing failed. [TimedOutError] Make sure your printer is connected

try this code below

const { PosPrinter } = require("electron-pos-printer");

data = [
        {
          type: "text", // 'text' | 'barCode' | 'qrCode' | 'image' | 'table
          value: "||---",
          style: {textAlign:'left',fontSize:'12px',margin:'0'},          
        },
        {
          type: "text", // 'text' | 'barCode' | 'qrCode' | 'image' | 'table
          value: "Test print<br><br>",
          style: {textAlign:'center',fontWeight:'700',fontSize:'18px',margin:'0'},
        },
        {
          type: "text", // 'text' | 'barCode' | 'qrCode' | 'image' | 'table
          value: "My printer",
          style: {textAlign:'center',fontWeight:'bold',fontSize:'14px',margin:'0'},
        },
        {
          type: "text", // 'text' | 'barCode' | 'qrCode' | 'image' | 'table
          value: "<br> "+ new Date(),
          style: {textAlign:'center',fontWeight:'bold',fontSize:'14px',margin:'0'},
        },
        {
          type: "text", // 'text' | 'barCode' | 'qrCode' | 'image' | 'table
          value: "---||",
          style: {textAlign:'right',fontSize:'12px',margin:'0'}          
        },
      ]
      const options = {
        preview: false, // Preview in window or print
        pageSize: '80mm',//  width of content body
        margin: "0 0 0 0", // margin of content body
        copies: 1, // Number of copies to print
        printerName: printerName, // printerName: string, check it at webContent.getPrinters()
        timeOutPerLine: 2000,
        silent: true,
      };
    
         
      const d = [...data];
       
        PosPrinter.print(d,options)
        .then(() => {
           console.log('printed successfully')
      
        })
        .catch((error) => {
           console.error(error);
       
        });

**Comment by janafsal** [comment]
> What version are you using by the way?

"electron-pos-printer": "^1.3.6"

**Comment by janafsal** [comment]
> const options = { silent: true, preview: false, margin: '0 0 0 0', copies: 1, printerName: 'POS-80C', timeOutPerLine: 4000, pageSize: "80mm" // page size }
> 
> ```
> const data = [{
> 	type: 'text',                                       // 'text' | 'barCode' | 'qrCode' | 'image' | 'table
> 	value: 'SAMPLE HEADING',
> 	style: {fontWeight: "700", textAlign: 'center', fontSize: "24px"}
> }]
> 
> PosPrinter.print(data, options).then(response => console.log(response)).catch(error => console.log(error))
> 
> 
> this is my configuration, 
> ```
> 
> And my error shows,
> 
> [23996:0620/204757.414:ERROR:print_render_frame_helper.cc(2302)] Printing failed. [TimedOutError] Make sure your printer is connected

this might be printer issues, check whether you have installed the latest driver...or check that your printer is online

**Comment by janafsal** [comment]
[1092:0605/115531.410:ERROR:print_render_frame_helper.cc(2264)] Printing failed.
even though i could print the error is still there....

**Comment by thsckdghks13** [comment]
Results of searching for information about ERROR:print_render_frame_helper.cc (2264)
Judging by an error related to chromium embedded with electron

I downgraded my previous electron @25.2.0 to electron @22.2.0 and there is no problem.
Try downgrading the electron version.

**Comment by janafsal** [comment]
But i am using electron 21.0 not 25

**Comment by Jerald042615** [comment]
> Results of searching for information about ERROR:print_render_frame_helper.cc (2264) Judging by an error related to chromium embedded with electron
> 
> I downgraded my previous electron @25.2.0 to electron @22.2.0 and there is no problem. Try downgrading the electron version.

You mean this specific version of electron resolves the issue?

**Comment by thsckdghks13** [comment]
![2520](https://github.com/Hubertformin/electron-pos-printer/assets/71646679/e3443a11-b027-408e-87a5-7a2985a3e1bf)

The corresponding error occurred in electron 25.2.0 version.

**Comment by helhablouj** [comment]
@thsckdghks13 Thank you, I had the exact same issue (printing not working when silent is true with the same error messages), and I managed to solve it by downgrading Electron to version 22.2 as you mentioned.

**Comment by Hubertformin** [comment]
This is a Chromium/Electron internal error (print_render_frame_helper) and not something we can fix in this library. Please check your Electron version and printer driver. Closing as upstream issue.
