### ISSUE TITLE
Change Orientation

### ISSUE THREAD

**Issue by rnleal** [Hubertformin/electron-pos-printer#11]
Is there anyway to change orientation of the contents? I would like to print to a receipt paper but the contents are printed on a landscape orientation. Thanks!

**Comment by Hubertformin** [comment]
Hello @rnleal ,
landscape orientation is not currently supported. Hopefully I'll see to that in the next version(s)

**Comment by rnleal** [comment]
Great..looking forward to it. How about doing multi column layouts? Is that possible? Sorry if Im asking lots of questions here. Wanted to know before you close this ticket

**Comment by Hubertformin** [comment]
Well, We'll see about that too
