### ISSUE TITLE
how can I control the paper length of the print?

### ISSUE THREAD

**Issue by kovlento** [Hubertformin/electron-pos-printer#12]
I want to print on a small sticker, how can I control the length of the print? I want to print one-fifth of the length of A4 paper

`        body {
            height: 100px;
            font-size: 12px;
            /*line-height: 24px;*/
        }`

I tried to modify the height of the body at `pos.html`, but it did not work

**Comment by sidneip** [comment]
i sended one pull request with this options,

#14 please check here.

**Comment by Hubertformin** [comment]
Check out @sidneip pull request #14
