### ISSUE TITLE
TimedOut

### ISSUE THREAD

**Issue by brkrtp** [Hubertformin/electron-pos-printer#2]
Hi i'm added windows printers to my printer and im use your example code then console says TimedOut
Pos Printers is TCP/IP

**Comment by iConrado** [comment]
Hi brkrtp, I had the same problem and I solved it by changing the timeOutPerline property.
Some devices are slower than others.
Example:
`options = {`
       `preview: false, // Preview in window or print`
        `width: '275px', //  width of content body`
        `margin: '0 0 30px 0', // margin of content body`
        `copies: 1, // Number of copies to print`
       `printerName: env.PRINTER, // printerName: string, check it at webContent.getPrinters()`
        `timeOutPerLine: 2000 // Two seconds of wait for each print instruction`
      `};`

**Comment by Hubertformin** [comment]
Hi @brkrtp, I’ll suggest the same solution given by @iConrado. I hope it works for you.

**Comment by almamlaka** [comment]
suggested by  @iConrado does not help for me only removing printerName works but cannot have more than one copie
