### ISSUE TITLE
The printer could not print "Preview" Windows 10

### ISSUE THREAD

**Issue by princeofnubia** [Hubertformin/electron-pos-printer#20]
It works fine on my windows 10 but when i deployed on a client system, I see The printer could not print "preview".

**Comment by Hubertformin** [comment]
Hello @princeofnubia 
Can I see your code snippet and the screenshot of the error console?

**Comment by princeofnubia** [comment]
It is working now. I had to set up the printer on the windows for a certain paper dimension and it started working. It was working on my local but when i used it client machine, it failed.
`    PosPrinter.print(arg.detail, arg.options)
        .then(() => {})
        .catch((error) => {
            throw error;
        });`

**Comment by Hubertformin** [comment]
Great!
I’m glad you found a solution.
