### ISSUE TITLE
TimeOut

### ISSUE THREAD

**Issue by yeyeyeyeonly** [Hubertformin/electron-pos-printer#23]
I print ten times like this
for(let i=0;i<10;i++){
        console.log(i);
        print();
}
The Printer successfully printed nine or ten receipt , but print callback shows error:TimeOut
PosPrinter.print(d, options)
      .then(() => {
        console.log("success");
      })
      .catch((error) => {
        console.log("error==="+error);
});

**Comment by vishwasskm** [comment]
The same issue occurs for me. I get a "Timeout" error after printing successfully!

**Comment by Silventino** [comment]
Same with me.

**Comment by Silventino** [comment]
Found the solution. You have to increase the timoutPerLine in the options:
```
const options = {
    preview: false,
    width: width,
    copies: copies, 
    printerName: printerName, 
    timeOutPerLine: 5000,  // THIS
    silent: true
  };
```
If you are printing to PDF, the TimeOut error may continue a problem

**Comment by kingkyle** [comment]
> Found the solution. You have to increase the timoutPerLine in the options:
> 
> ```
> const options = {
>     preview: false,
>     width: width,
>     copies: copies, 
>     printerName: printerName, 
>     timeOutPerLine: 5000,  // THIS
>     silent: true
>   };
> ```
> 
> If you are printing to PDF, the TimeOut error may continue a problem

Increased the time. its just stuck not printing

**Comment by gakyoo** [comment]
Getting same error, and still TimingOut from main process

**Comment by sKY02644** [comment]
im still getting timeout after increasing timeOutPerLine: 5000,  // THIS

**Comment by felipemarques** [comment]
same error here TimedOut

**Comment by Cardozo1w** [comment]
It was working well, and now I'm receiving the same error:/

**Comment by engosamamohsen** [comment]
@sKY02644 @gakyoo @Cardozo1w @haotrg035 @Silventino 
Do you find a solution for a timeout or used another package?

**Comment by lodekib** [comment]
> It was working well, and now I'm receiving the same error:/

Can't get it even to work.!

**Comment by viktorrm** [comment]
Another solution? or package? it doesn't work, the error persists.

**Comment by Cardozo1w** [comment]
> Another solution? or package? it doesn't work, the error persists.

I can help you

**Comment by viktorrm** [comment]
Thanks!, I have done everything that the documentation recommends, but i don't have a printer now, so i think  the library is looking for a printer and then doesn't find anything, just throws the error "timedOut". The problem propably is havent a printer?

**Comment by viktorrm** [comment]
> > Another solution? or package? it doesn't work, the error persists.
> 
> I can help you

Thanks!, I have done everything that the documentation recommends, but i don't have a printer now, so i think the library is looking for a printer and then doesn't find anything, just throws the error "timedOut". The problem propably is havent a printer?

**Comment by viktorrm** [comment]
> > > Another solution? or package? it doesn't work, the error persists.
> > 
> > 
> > I can help you
> 
> Thanks!, I have done everything that the documentation recommends, but i don't have a printer now, so i think the library is looking for a printer and then doesn't find anything, just throws the error "timedOut". The problem propably is havent a printer?

ok, creo que hablas español, acabo de conectar una impresora pero sigue de igual manera el error timedOut. Tampoco me funciona el preview

![Screenshot from 2022-03-22 18-02-48](https://user-images.githubusercontent.com/50388649/159596283-5a0a0ea5-4c89-4424-b1f0-afecc9b3b957.png)


![Screenshot from 2022-03-22 17-57-19](https://user-images.githubusercontent.com/50388649/159596151-3f51f9ce-bacd-45cd-a142-1da9910d20bd.png)
![Screenshot from 2022-03-22 17-57-19](https://user-images.githubusercontent.com/50388649/159596183-cbf2186b-e912-428e-8abe-d544007b88be.png)

**Comment by Cardozo1w** [comment]
> > > > Another solution? or package? it doesn't work, the error persists.
> > > 
> > > 
> > > I can help you
> > 
> > Thanks!, I have done everything that the documentation recommends, but i don't have a printer now, so i think the library is looking for a printer and then doesn't find anything, just throws the error "timedOut". The problem propably is havent a printer?
> 
> ok, creo que hablas español, acabo de conectar una impresora pero sigue de igual manera el error timedOut. Tampoco me funciona el preview. Estoy usando Electronjs y la impresora no es tipo pos-thermal printer
> 
> ![Screenshot from 2022-03-22 18-02-48](https://user-images.githubusercontent.com/50388649/159596283-5a0a0ea5-4c89-4424-b1f0-afecc9b3b957.png)
> 
> 
> ![Screenshot from 2022-03-22 17-57-19](https://user-images.githubusercontent.com/50388649/159596151-3f51f9ce-bacd-45cd-a142-1da9910d20bd.png)
> 
> ![Screenshot from 2022-03-22 17-57-31](https://user-images.githubusercontent.com/50388649/159596349-c357c034-e554-414b-ab3c-80763933bd34.png)
> 
> 

Yo use silent false, pero si estoy usando una impresora térmica, mañana haré unas pruebas con otro tipo de impresora, en tiempo por línea utilice 5000, puedes mandarme un correo oscar1w2e@gmail.com y checamos tu detalle

**Comment by viktorrm** [comment]
> [oscar1w2e@gmail.com](mailto:oscar1w2e@gmail.com)

Muchas gracias, te envié un correo.

**Comment by viktorrm** [comment]
> > > > > Another solution? or package? it doesn't work, the error persists.
> > > > 
> > > > 
> > > > I can help you
> > > 
> > > 
> > > Thanks!, I have done everything that the documentation recommends, but i don't have a printer now, so i think the library is looking for a printer and then doesn't find anything, just throws the error "timedOut". The problem propably is havent a printer?
> > 
> > 
> > ok, creo que hablas español, acabo de conectar una impresora pero sigue de igual manera el error timedOut. Tampoco me funciona el preview. Estoy usando Electronjs y la impresora no es tipo pos-thermal printer
> > ![Screenshot from 2022-03-22 18-02-48](https://user-images.githubusercontent.com/50388649/159596283-5a0a0ea5-4c89-4424-b1f0-afecc9b3b957.png)
> > ![Screenshot from 2022-03-22 17-57-19](https://user-images.githubusercontent.com/50388649/159596151-3f51f9ce-bacd-45cd-a142-1da9910d20bd.png)
> > ![Screenshot from 2022-03-22 17-57-31](https://user-images.githubusercontent.com/50388649/159596349-c357c034-e554-414b-ab3c-80763933bd34.png)
> 
> Yo use silent false, pero si estoy usando una impresora térmica, mañana haré unas pruebas con otro tipo de impresora, en tiempo por línea utilice 5000, puedes mandarme un correo [oscar1w2e@gmail.com](mailto:oscar1w2e@gmail.com) y checamos tu detalle


Muchas gracias, te envié un correo.

**Comment by Hubertformin** [comment]
> > > Another solution? or package? it doesn't work, the error persists.
> > 
> > 
> > I can help you
> 
> Thanks!, I have done everything that the documentation recommends, but i don't have a printer now, so i think the library is looking for a printer and then doesn't find anything, just throws the error "timedOut". The problem propably is havent a printer?

Yes, if you don't have a printer installed, set `options.preview` to `true`

**Comment by Hubertformin** [comment]
Hello Everyone!
Please update to the latest version of this package.

**Comment by viktorrm** [comment]
> Hello Everyone! Please update to the latest version of this package.

i got the same error, [TimedOutError] Make sure your printer is connected

**Comment by Mikael-R** [comment]
Same problem here, I think is the last update in electron

**Comment by abdulbasit0-UI** [comment]
I got the solution working on electron v 9 and electron-pos-printer v1.2
