### ISSUE TITLE
Not print in production

### ISSUE THREAD

**Issue by hsumyatthu** [Hubertformin/electron-pos-printer#31]
Print is work in development version but not work in production version.
Can check preview page
my electron version is
`"electron": "9.3.5",`
my electron-pos-printer version is
`"electron-pos-printer": "^1.2.4",`

**Comment by agussugiatno** [comment]
yes it's couse timeout when printing at then end send error, when it in developing got message :(node:16804) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 render-line-reply listeners added to [IpcMainImpl]. Use emitter.setMaxListeners() to increase limit .
