### ISSUE TITLE
Paper size

### ISSUE THREAD

**Issue by didierpasuy** [Hubertformin/electron-pos-printer#32]
How can you determine a variable paper size?

As for example that of a POS document

**Comment by kalnado** [comment]
For me setting paper size  in micrometers worked, i.e. for 100m x 75mm labels I set:

```
const options = {
   ..
   pageSize: { height: 75000, width: 100000 }
};
```

**Comment by sKY02644** [comment]
contents are not fitting in the center how do i center the contents in the center
