### ISSUE TITLE
Add font family

### ISSUE THREAD

**Issue by yuniit** [Hubertformin/electron-pos-printer#35]
Hello, 
How can I add font-family to print content  I've tried :
```js 
   {
       type: 'text',
       value: 'Company Name',
       style: `text-align:center; font-size: 20px; margin: 0; padding-bottom: 10px;`,
       css: { 'font-family': 'Bahnschrift' },
    },
```

But after print I got default font family.
Please correct me if i am wrong. Thank

**Comment by xjuanc** [comment]
I'm wondering the same, have you found a way?

**Comment by yuniit** [comment]
@xjuanc  I just add @font-face to my css and it worked.

**Comment by Hubertformin** [comment]
I am glad it worked for you!

**Comment by MadhabaPatra** [comment]
> @xjuanc I just add font-face to my css and it worked.

can you please elaborate or send the exact code here , thank you
