### ISSUE TITLE
Add option to give styles to the td of the tables

### ISSUE THREAD

**Issue by ldavidsp** [Hubertformin/electron-pos-printer#36]

**Comment by vishwasskm** [comment]
`tableBody: [
      [
	      {
		      type: 'text',
		      value: 'Base Total:',
		      css: {
			      'text-align': 'right',
		      },
	      },
	      {
		      type: 'text',
		      value: `Rs. ${format_number(sale.base_total_mrp)}`,
		      css: {
			      'text-align': 'left',
		      },
	      },
      ],
]`

**Comment by Hubertformin** [comment]
Hello 
Can you look at the new update?
