### ISSUE TITLE
body-init error

### ISSUE THREAD

**Issue by dmitryshelomanov** [Hubertformin/electron-pos-printer#42]
require is not defined

**Comment by dmitryshelomanov** [comment]
we need to add  contextIsolation: false in webPreferences "electron": "^12.0.5",

**Comment by inubayuaji** [comment]
I also had this problem. I solved this problem by adding `contextIsolation: false` in pos-printer.js file line 93. 
```js
var mainWindow = new BrowserWindow({
    width: 210,
    height: 1200,
    show: !!options.preview,
    webPreferences: {
        nodeIntegration: true,
        contextIsolation: false // here
    }
});
```
Note: this is in the module file not in the main project file.
