### ISSUE TITLE
Error: Cannot find module 'electron-pos-printer', vue-electron

### ISSUE THREAD

**Issue by Ahmed-dev-vpc** [Hubertformin/electron-pos-printer#46]
In my case I use Vue-electron, It works fine in case development mode 
But this problem only appears in production mode...

![Capture](https://user-images.githubusercontent.com/58576140/117861681-fb3ccd00-b291-11eb-8dd2-b90c07e94957.PNG)

**Comment by Drewdan** [comment]
Did you find a solution to this?

**Comment by Ahmed-dev-vpc** [comment]
> Did you find a solution to this?

not yet :(

**Comment by O-ID** [comment]
> If you are using electron 12 or greater just move to `ipcMain` and `ipcRenderer`, I've tried also `@electron/remote` but it's the same error.
> 
> Code example:
> 
> ```js
> // === in renderer code
> 
> import { ipcRenderer } from 'electron';
> 
> // in some async function ...
> const printers = await ipcRenderer.invoke('serivce-printer-list');
> const data = [ ... ]; // data to print
> const options = {
>   printerName: printers[0], // a printer from the printers list
>   // ... other options
> };
> try {
>   await ipcRenderer.invoke('serivce-printer-print', (data, options));
> } catch(err) {
>   console.error(err);
> }
> 
> // === in main code
> 
> const { app, BrowserWindow, ipcMain } = require('electron');
> const { PosPrinter } = require('electron-pos-printer');
> 
> // main window init logic
> const mainWindow = new BrowserWindow({ ... });
> 
> ipcMain.handle('service-printer-list', async () => {
>   const webContents = mainWindow.webContents;
>   const printers = webContents.getPrinters();
> 
>   return printers;
> });
> 
> ipcMain.handle('service-printer-list', async (data, options) => PosPrinter.print(data, options));
> ```

I try this and modify the code it's working, but the printer doesn't do anything. i try set print `preview: true` in options, it run but not showing of the content.
after I inspect the element an error appears:

![image](https://user-images.githubusercontent.com/45619816/120267109-7a3f8700-c2cd-11eb-897b-c5feedec1485.png)

and this my code.
```js
 // === in main code ( background.js )
import { app, protocol, BrowserWindow, ipcMain } from 'electron'
const { PosPrinter } = require('electron-pos-printer');
const mainWindow = new BrowserWindow({ ... });
const options = {
    preview: true, // Preview in window or print
    width: 250, //  width of content body
    margin: "0px 0px 0px -10px", // margin of content body
    copies: 1, // Number of copies to print
    printerName: 'POS58 Printer(3)', // printerName: string, check it at webContent.getPrinters()
    timeOutPerLine: 500,
    silent: true,
  };
  ipcMain.handle('service-printer-print', (data) =>{
    PosPrinter.print(data, options);
  });

// === in renderer code ( invoice.vue )
import { ipcRenderer } from 'electron';
export default{
  data(){
      return {
          datass:[]
      }
  }
  methods: {
      async printr() {
            try {
              await ipcRenderer.invoke('service-printer-print', (this.datass));
            } catch(err) {
              console.error(err);
            }
      },
  }
}
```
And i try disable webSecurity in my `vue.config.js` but still not working.
how about this?

**Comment by Ahmed-dev-vpc** [comment]
@robert52 @O-ID  @Drewdan  @sidneip 
Hi guys
Are there other packages that do the same thing as an electron-post-printer?

**Comment by Drewdan** [comment]
I created a custom implementation of my own to handle printing using an EPOS printer, it created headings, paragraphs and tables. I can pull this into a package and put some docs together is people are interested

**Comment by Drewdan** [comment]
@Ahmed-dev-vpc https://www.npmjs.com/package/electron-epos-printer - created this package, it does not do as much as this one, but it builds for me. Feel free to open some issues if you want to see extra features in it.

**Comment by davimatos** [comment]
I have the same problem. It only happens in production. Any solution? :(

**Comment by Drewdan** [comment]
I believe it is an error with the node version, possibly reverting to an older version resolves it, but not ideal and this will probably upset some other package you are using. This is why I made my own package, though I have not utilized it in a while, so I am not sure how well it is working with the current version of node

**Comment by davimatos** [comment]
> I believe it is an error with the node version, possibly reverting to an older version resolves it, but not ideal and this will probably upset some other package you are using. This is why I made my own package, though I have not utilized it in a while, so I am not sure how well it is working with the current version of node

Thanks for help. Is there documentation for this package you created, or does it work the same as this one?

**Comment by davimatos** [comment]
> I believe it is an error with the node version, possibly reverting to an older version resolves it, but not ideal and this will probably upset some other package you are using. This is why I made my own package, though I have not utilized it in a while, so I am not sure how well it is working with the current version of node

Thanks for help. Do you have documentation for this package you created, or does it work the same as this one?

**Comment by davimatos** [comment]
After exhausting days of searching and debugging, I found the solution to the problem!!

Apparently it's an import error from the "vue-cli-plugin-electron-builder" package. [See docs](https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#native-modules)

You just need to add the following configuration:

```
// vue.config.js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      // List native deps here if they don't work
      externals: ['electron-pos-printer'],
      // If you are using Yarn Workspaces, you may have multiple node_modules folders
      // List them all here so that VCP Electron Builder can find them
      nodeModulesPath: ['../../node_modules', './node_modules']
    }
  }
}
```

**Comment by Ahmed-dev-vpc** [comment]
C After exhausting days of searching and debuggingV I found the solution to the problem!!
C 
C Apparently it's an import error from the "vue-cli-plugin-electron-builder" packageC FSee docsD(https:LLnklaymanCgithubCioLvue-cli-plugin-electron-builderLguideLguideChtml#native-modules)
C 
C You just need to add the following configuration:
C 
C ```
C LL vueCconfigCjs
C moduleCexports = V
C   pluginOptions: V
C     electronBuilder: V
C       LL List native deps here if they don't work
C       externals: F'electron-pos-printer'DV
C       LL If you are using Yarn WorkspacesV you may have multiple node_modules folders
C       LL List them all here so that VCP Electron Builder can find them
C       nodeModulesPath: F'CCLCCLnode_modules'V 'CLnode_modules'D
C     C
C   C
C C
C ```

Yeah, that's what happened to me too :) 
After a very hard search, this was just the solution

**Comment by Ahmed-dev-vpc** [comment]
@davimatos 
Yeah, that's what happened to me too :)
After a very hard search, this was just the solution

// vue.config.js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      ....
      externals: ['electron-pos-printer'],
      ...
    }
  }
}
