### ISSUE TITLE
How could you print faster with the silent 'true "option?

### ISSUE THREAD

**Issue by rafaelvaloto** [Hubertformin/electron-pos-printer#5]
Hello when "silent" is set to "false", printing is fast, when "true" is printing is slow. How could you print faster with the silent 'true "option?

**Comment by Hubertformin** [comment]
Hello @refaelvaloto,
What version of electron are you using?
Check this out https://stackoverflow.com/questions/57302311/silent-print-is-not-working-electron-js

**Comment by rafaelvaloto** [comment]
I'm using v9.1.0, the silent option is working correctly, the problem that printing is slower when it is set to true

**Comment by Hubertformin** [comment]
Hello @rafaelvaloto 
I apologize for the delay. I've had the same issue with silent print in general with some electron versions. So at the point, I am thinking this is an issue that has to do with electron itself. 
But I keep working on how to resolve this.
