### ISSUE TITLE
How do working in react & typescript environment?

### ISSUE THREAD

**Issue by Louis-jk** [Hubertformin/electron-pos-printer#52]
Thank you for creating this great module.
Please Help me.
How can I make this package work in react & typescript environment?

**Comment by Hubertformin** [comment]
Hello @Louis-jk 
Excuse my late replies. Can state exactly the issues you are facing?

**Comment by Louis-jk** [comment]
> Hello @Louis-jk Excuse my late replies. Can state exactly the issues you are facing?

Hello @Hubertformin 
Thanks for your reply.
Rather, I'm sorry I saw your reply so late.
I was using typescript and react at the time, and I solved it in a different way.
sorry for late reply. And thank you for contacting me.

**Comment by Hubertformin** [comment]
I am glad your found a solution @Louis-jk
