### ISSUE TITLE
with electron 12 this module not working

### ISSUE THREAD

**Issue by aashhshah** [Hubertformin/electron-pos-printer#55]
I tried with electron 9(it's working)but with electron 12 it not working.it shows timedOut error.I also increase timeOutPerLine.but it's not working

**Comment by davimatos** [comment]
I have the same problem. Someone help?

**Comment by davimatos** [comment]
Here's a solution that worked for me: https://github.com/Hubertformin/electron-pos-printer/issues/47#issuecomment-871138049

**Comment by aashhshah** [comment]
> Here's a solution that worked for me: [#47 (comment)](https://github.com/Hubertformin/electron-pos-printer/issues/47#issuecomment-871138049)

still not working

**Comment by Hubertformin** [comment]
Hello @aashhshah, can you update to the latest version of the package and try again?
