### ISSUE TITLE
Printing in a loop to automate

### ISSUE THREAD

**Issue by tmblog** [Hubertformin/electron-pos-printer#56]
Hi thank you for the module it works nicely. I am running into some issues whilst calling the print function in a loop, in essence, I change the value of `data.value` and call print. It happens so quick that it doesn't overwrite the variable and prints only the first one.
I suppose a timer would do the trick but if there was a native way to delay it maybe I am missing something?
Here's some code to clarify:
```
function print(order) {
  const data = [
	{
      type: 'text',
      value: order.content,
        },
     ]

    PosPrinter.print(data, options)
      .then(() => {})
      .catch((error) => {
        console.error(error);
      });
}
```
Calling the `print()` function
```
for(let order of content) {
print(order);
}
```
Any pointers will be highly appreciated!

**Comment by Hubertformin** [comment]
I will advice you to use a loop to construct the data array, then when the loop is finished, you then print the data.
