### ISSUE TITLE
Its possible print to network POS Printer?

### ISSUE THREAD

**Issue by alejuanito** [Hubertformin/electron-pos-printer#57]
is it possible to specify only the ip of the printer and print it?
In the documentation I see that the name can be specified but I do not know if it is possible to do it by ip

**Comment by Hubertformin** [comment]
As of now, it is not possible to print over your network. Hopefully, in the future versions, I can make that happen

**Comment by limsocheat** [comment]
> As of now, it is not possible to print over your network. Hopefully, in the future versions, I can make that happen

Hi, any update on this? can we print to multiple network printer?
