### ISSUE TITLE
TimedOut Error

### ISSUE THREAD

**Issue by sKY02644** [Hubertformin/electron-pos-printer#59]
Working with  quasar a vuejs framework  PosPrinter retrurn TimedOut error 

code in electron main
`ipcMain.handle('posPrint', (_event, {data, posoptions}) => {
  PosPrinter.print(JSON.parse(data), posoptions)
  .then(() => {})
  .catch(err => {
    console.log(err)
  })
});`

Code in preload 
`
contextBridge.exposeInMainWorld('serivcePrinterPrint', {
      print_service: (data: { data: PosPrintData, posoptions: PosPrintOptions }) => ipcRenderer.invoke('posPrint', data),
})`

**Comment by AnggaIPT** [comment]
I got same issue. how to fix it ?

**Comment by sKY02644** [comment]
i had to downgrade to electron 

`"electron": "^9.1.0"`

and it works

im still keeping taps on when this fix will be done before i upgrade

**Comment by sKY02644** [comment]
I also had this problem. I solved this problem by adding contextIsolation: false in pos-printer.js file line 93.

`var mainWindow = new BrowserWindow({
    width: 210,
    height: 1200,
    show: !!options.preview,
    webPreferences: {
        nodeIntegration: true,
        contextIsolation: false // here
    }
});`

Note: this is in the module file not in the main project file.
