### ISSUE TITLE
Get TimedOut Error In Electron 13 and React

### ISSUE THREAD

**Issue by AnggaIPT** [Hubertformin/electron-pos-printer#60]
Thank for developing this module, but i got time out error
 Can you help me to fix this problem ?

**Comment by felipemarques** [comment]
i have the same error

**Comment by 15309294916** [comment]
> i have the same error



> 我有同样的错误
are you solve the problem?

**Comment by 15309294916** [comment]
> i have the same error

when i use electron version 13,make this error,I use the verson 11 to instead it,slove the error,you can try it

**Comment by janafsal** [comment]
We need to edit pos-printer.ts and compile again (or) edit pos-printer.js in dist directly. Add webPreferences: { nodeIntegration: true, contextIsolation: false, } in line no.91 (new BrowserWindow)

**Comment by treeindark** [comment]
is there's an update ?

**Comment by lodekib** [comment]
how exactly?

**Comment by janafsal** [comment]
> is there's an update ?

https://github.com/Hubertformin/electron-pos-printer/issues/60#issuecomment-1068271541

**Comment by janafsal** [comment]
> We need to edit pos-printer.ts and compile again (or) edit pos-printer.js in dist directly. Add webPreferences: { nodeIntegration: true, contextIsolation: false, } in line no.91 (new BrowserWindow)



> how exactly?

https://github.com/Hubertformin/electron-pos-printer/issues/60#issuecomment-1068271541

**Comment by sara-jegorova** [comment]
@Hubertformin @sidneip @jfamousket Please create a new release with the fix from https://github.com/Hubertformin/electron-pos-printer/pull/53

**Comment by janafsal** [comment]
go to node modules in your project =>electron-pos-printer=>dist(folder) => need to edit pos-printer.ts and compile again (or) edit pos-printer.js directly.in line no.91 (new BrowserWindow) Add webPreferences: { nodeIntegration: true, contextIsolation: false, } 

then it will work :-) happy printing

**Comment by sara-jegorova** [comment]
@janafsal Sorry but changing node_modules files is not the way to go. It won't work if the project gets built via github actions or from other people's pc's (they would also have to manually make the change).

**Comment by zawzawwin-dev** [comment]
> We need to edit pos-printer.ts and compile again (or) edit pos-printer.js in dist directly. Add webPreferences: { nodeIntegration: true, contextIsolation: false, } in line no.91 (new BrowserWindow)

It is working!!

**Comment by Hubertformin** [comment]
Hello @everyone
This issue has been fixed, it is not compatible with the latest version of electron
