### ISSUE TITLE
Page Size

### ISSUE THREAD

**Issue by sKY02644** [Hubertformin/electron-pos-printer#61]
Please assist me center the contents

`const options = {
    preview: false, // Preview in window or print
    width: widthPage, //  width of content body
    margin: "0 0 0 0", // margin of content body
    copies: 1, // Number of copies to print
    printerName: printerName, // printerName: string, check it at webContent.getPrinters()
    timeOutPerLine: 400,
    silent: true,
    pageSize: { height: 75000, width: 100000 }
  };
`

![WhatsApp Image 2022-01-06 at 12 19 43 PM](https://user-images.githubusercontent.com/25549285/148382212-4dfef184-9424-41b4-87e8-7fc99c1d8661.jpeg)

**Comment by sKY02644** [comment]
@Hubertformin Please assist

**Comment by sKY02644** [comment]
Had no response

**Comment by Hubertformin** [comment]
Hello @sKY02644 
Please forgive for my delay, I saw you issue and I am working on fixing it ASAP!!

**Comment by sKY02644** [comment]
Thank you for your response it will do me much good

because i had to fall back on a different package but once its fixed i will
move back to urs

thanks again

**Comment by sKY02644** [comment]
@Hubertformin 

Hope all is well

Please how far with the fix

**Comment by davimatos** [comment]
Are you sure you are setting the paper size correctly? It seems to me that the defined width is larger than what is needed for your paper.

Have you tried decreasing the width? In my case, if I decrease the width, I don't need to center it, since the content will occupy all printable area.

**Comment by Hubertformin** [comment]
Can you try again?

**Comment by sKY02644** [comment]
does it support 80mm paper now?

**Comment by Hubertformin** [comment]
Yes, it does. You can modify the `pageSize.width` to `303`. That should work well.

**Comment by sKY02644** [comment]
okay i will take note of this and use it

i was hacking my way using all sorts of packages 

will give it a try end of this week or early next month thanks boss 👍👍👍

**Comment by Hubertformin** [comment]
Yes, set the `pageSize: {width: 303, height: 1200}` For example, that is approximate dimension of 80mm paper

**Comment by sKY02644** [comment]
thank you soo much 

i will revert later💯
