### ISSUE TITLE
Need more documentation

### ISSUE THREAD

**Issue by fssonca** [Hubertformin/electron-pos-printer#7]
Thank so much  to the author. Help me a lot. But, in the began, this project didnt work for me . It's because the **nodeIntegration: true,**  in main.js. But, i have a project for your guys: https://github.com/fssonca/electron-printer . Clone and enjoy.

Oh, one more thing: _< meta >_ tags that come with the electron-quick-start. I disabled them because i got a lot of errors.

**Comment by Hubertformin** [comment]
@fssonca Good job
