### ISSUE TITLE
Error: height and width properties must be minimum 352 microns.

### ISSUE THREAD

**Issue by melhadidy572** [Hubertformin/electron-pos-printer#81]
Hi,
appreciate your support,
I'm using  electron-pos-printer 1.3.4 in vue/electron project,
when I trigger it it give me this error in the console.
-->Error: height and width properties must be minimum 352 microns.

**Comment by Hubertformin** [comment]
Hello @melhadidy572 
Can I see your code with a screenshot of the error stack?

**Comment by noah2000** [comment]
@Hubertformin  
Electron[7144:113857] Warning: Expected min height of view: (<NSPopoverTouchBarItemButton: 0x7f9456a49a50>) to be less than or equal to 30 but got a height of 32.000000. This error will be logged once per view in violation.|

**Comment by noah2000** [comment]
```js
const options = {
    preview: false, 
    margin: "auto", 
    copies: 1, 
    printerName: "EPSON LQ-310", 
    timeOutPerLine: 1000,
    pageSize: "80mm",
  };
  ```
> when  ``` preview = false```
node:  v14.18.3 
electron: ^10.0.0"

`Error: height and width properties must be minimum 352 microns.
    at WebContents._.print (electron/js2c/browser_init.js:157:7237)
    at /Users/admin/Documents/project/**/electron-printer/node_modules/electron-pos-printer/dist/index.js:1:2307`
    
  >

**Comment by Hubertformin** [comment]
Okay, Thank you. I will look into that.
