### ISSUE TITLE
Barcode position doesn't work

### ISSUE THREAD

**Issue by tguillaume02** [Hubertformin/electron-pos-printer#85]
I would like center barcode but this doesn't work (work only with image and qrCode)

`    
    {
        type: 'barCode',
        value: '4810574',
        height: 20,    
        width: 1,   
        displayValue: false,   
        fontsize: 8,
        style:{position: 'center'},
        position: 'center
    }`
![image](https://user-images.githubusercontent.com/11637270/209636631-17055ad8-f22e-46b9-98ff-7485a7420513.png)

**Comment by Hubertformin** [comment]
Hello, 
The problem with this is you set the position in the style object. You could just specify that in the root object. 
```js
{ type: 'barCode', ... position: 'center' }
```

**Comment by tguillaume02** [comment]
Same problem
 { type: 'barCode', value: '4810574', height: 20,     width: 1,    displayValue: false,    fontsize: 8, position: 'center }

**Comment by Hubertformin** [comment]
Hello again,
You forgot to add a trailing ' at the end of `center`. Try this
```js
{ type: 'barCode', value: '4810574', height: 20, width: 1, displayValue: false, fontsize: 8, position: 'center }
```

**Comment by sKY02644** [comment]
@Hubertformin @Hubertformin @Hubertformin  

```
{
      type: 'barCode',
      value: '023456789010',
      height: "46",                     // height of barcode, applicable only to bar and QR codes
      width: "2",                       // width of barcode, applicable only to bar and QR codes
      displayValue: false,             // Display value below barcode
      fontsize: 24,
      position: "center",
    },
```
    
**barCode doesnt center on 80mm**
    
 its urgent i have to have it ready by tomorrow and this is the only thing left

**Comment by Saltys-Git** [comment]
> Hello again, You forgot to add a trailing ' at the end of `center`. Try this
> 
> { type: 'barCode', value: '4810574', height: 20, width: 1, displayValue: false, fontsize: 8, position: 'center' }

tried printing your same code, but still it doesn't align itself to center.
