### ISSUE TITLE
Types on dist 

### ISSUE THREAD

**Issue by amaury-tobias** [Hubertformin/electron-pos-printer#9]
on `dist/models.d.ts`
tableHeader, tableBody and tableFooter are no optionals
so it fails if i dont set these options

**Comment by Hubertformin** [comment]
I’m sorry for this 
I’ll fix this as soon as possible.

**Comment by Hubertformin** [comment]
@amaury-tobias 
Issue fixed, update to v1.2.1.
Thanks for your patience!
